#https://github.com/realm/SwiftLint/issues/1732
#https://github.com/realm/SwiftLint/blob/master/Rules.md

custom_rules:
    # prefer_https:
    #   name: "Prefer HTTPS over HTTP"
    #   regex: "((?i)http(?!s))"
    #   match_kinds: string
    #   message: "HTTPS should be favored over HTTP"
    #   severity: warning

disabled_rules:
  - trailing_whitespace
  - line_length
  - nesting
  - empty_parentheses_with_trailing_closure
  - statement_position

opt_in_rules:
  - empty_count
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - no_extension_access_modifier
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - attributes
  - discarded_notification_center_observer
  - empty_parameters
  - legacy_constant
  - legacy_constructor
  - mark
  - redundant_discardable_let
  - shorthand_operator
  - syntactic_sugar
  - weak_delegate
  # - object_literal

excluded:
  - Carthage
  - Pods

cyclomatic_complexity:
  warning: 15
  error: 30
force_cast: error
force_unwrapping: error
force_try: warning
line_length: 120
type_body_length:
  warning: 300
  error: 400
file_length:
  warning: 500
  error: 1200
function_body_length:
  warning: 80
  error: 160
identifier_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
type_name:
  min_length: 1
  max_length:
    warning: 40
    error: 50
attributes:
    severity: error
    always_on_same_line: ["@IBAction", "@NSManaged"]
    always_on_line_above: []
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
